// <auto-generated />
using System;
using BrickFactoryBeat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrickFactoryBeat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202203117_AddDuration")]
    partial class AddDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrickFactoryBeat.Domain.Equipment.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("BrickFactoryBeat.Domain.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquipmentId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentId1")
                        .IsUnique()
                        .HasFilter("[EquipmentId1] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BrickFactoryBeat.Domain.StateHistory.StateHistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OldState")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OrderId");

                    b.ToTable("StateHistory");
                });

            modelBuilder.Entity("BrickFactoryBeat.Domain.Orders.Order", b =>
                {
                    b.HasOne("BrickFactoryBeat.Domain.Equipment.Equipment", "Equipment")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrickFactoryBeat.Domain.Equipment.Equipment", null)
                        .WithOne("CurrentOrder")
                        .HasForeignKey("BrickFactoryBeat.Domain.Orders.Order", "EquipmentId1");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BrickFactoryBeat.Domain.StateHistory.StateHistoryRecord", b =>
                {
                    b.HasOne("BrickFactoryBeat.Domain.Equipment.Equipment", "Equipment")
                        .WithMany("StateHistory")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrickFactoryBeat.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Equipment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BrickFactoryBeat.Domain.Equipment.Equipment", b =>
                {
                    b.Navigation("CurrentOrder");

                    b.Navigation("Orders");

                    b.Navigation("StateHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
